### PR TITLE
Fix overlapping breakpoints on Seedlings; remove Adapt

### PR DESCRIPTION
**Pull request by jritterbush**
## Description:

- Fixes a bug where responsive type and REM breakpoints was leading to multiple breakpoints being active at once.
	- The px values were chosen based on where our current breakpoint values (~16px * REM-VALUE)
- Also fixed issue on medium breakpoint where the top of the range was the same as the bottom of the large range. Now it subtracts 1 pixel from this value to ensure no overlap.
- Remove Adapt styles (Adapt has been shut down)
- Remove unused `$small-width` from seedlings-marketing (we use `min-width` for media queries so medium and large are the only 2 needed)

## Testing

> For the time being (so I could get Stanton's new homepage in it)

Feel free to check most pages for this, but basically any page at the 960px breakpoint is where the issue was happening. Both the `-m` and `-l` utilities were firing so weird things were happening. Now 959px will be the last `-m` and 960px will be when `-l` starts.

See below for a couple of examples with screenshots:

### Current homepage

👀 See the "Solutions for every role on your social media team" section at the bottom of the page

- [Stanton's test site](https://stanton-test.stagely.sproutsocial.com/): 
	Screen Shot 2021-01-15 at 2 43 27 PM
- [Compare to prod homepage](https://sproutsocial.com/)
	Screen Shot 2021-01-15 at 2 43 10 PM

### New homapage

👀 See the new testimonial carousel

- [Stanton's test site](https://stanton-test.stagely.sproutsocial.com/homepage-2021/?amp):
	Screen Shot 2021-01-15 at 2 53 12 PM
- Compare to previous version (not on prod so just screenshot): 
	Screen Shot 2021-01-14 at 9 08 06 AM

### CODE REVIEW

**Comment by conwaydev** [comment]
You can also remove Bambu

**Review by conwaydev — DISMISSED** [review]

**Comment by conwaydev** [comment]
also the webapp is no longer in use either

**Comment by jritterbush** [comment]
@conwaydev gone. I know it is just the dist code, but it is very satisfying to delete 45K lines of code.

**Review by conwaydev — APPROVED** [review]

**Review by stanton47 — APPROVED** [review]
Thanks so much for getting this together and doing other cleanup as you went!

**Pull request merged**
