### PR TITLE
DAR-34 - chore(seeds-depth): adding new build of seeds-depth package

### PR DESCRIPTION
**Pull request by iamtheozzy**
## Description:
I didn't realize we include the `/dist` directory in git. This PR adds the new build to `seeds-depth/dist`  and should fix jenkins pipeline.

## Jira:
https://sprout.atlassian.net/browse/DAR-34?atlOrigin=eyJpIjoiOWRhNThjOGRlOGVhNGQyMzk4YmY2MTkwNThmOWU1NjYiLCJwIjoiaiJ9

### CODE REVIEW

**Review by bfoehring — APPROVED** [review]

**Review by conwaydev — APPROVED** [review]

**Comment by conwaydev** [comment]
@iamtheozzy ya i've been burned by this too, technically we probably shouldn't include the `/dist/` directory in git but still have lerna publish them appropriately. I don't really have the bandwidth to fix right now, but I think may be a nice backlog ticket.

**Comment by iamtheozzy** [comment]
> 

Yea I was spinning in my chair trying to figure out why it didn't work. I can write up a ticket to address this. I'm also not sure if we need the "merge to develop and then merge to main" strategy so we might as well review that process at the same time.

**Comment by conwaydev** [comment]
@iamtheozzy haha sorry about that, its been our git-flow forever, it used to be a failsafe in case anything got merged into `develop` that may cause regressions, it would make the `main` branch responsible for publishing the packages (as you may be aware, unpublishing in NPM is a bit of a nightmare). I think we could very easily remove that step in the JENKINSFILE, but again there may be a better way in general to handle git flow for these packets.

**Comment by iamtheozzy** [comment]
@conwaydev no worries! Yea unpublishing is the worst! I've had a time I accidentally deployed breaking change as a minor update 😓 . I throw a ticket out and tag you In case you want to be a part of the process.

**Pull request merged**
