### PR TITLE
[WEBGUILD-6388] feat: add typescript support

### PR DESCRIPTION
**Pull request by benthemonkey**
## Description:

- Adds a `dist/seeds-[module].d.ts` file to each packet
- references that file in the package.json as `"types": "dist/seeds-[module].d.ts"`

Tested locally be linking to a project where I'm converting a repo to typescript 😈 

## GitHub pages build link:

I'm  not sure where this would fit into the seeds docs. Feedback welcome.

## Jira:

https://sprout.atlassian.net/browse/WEBGUILD-6388

### CODE REVIEW

**Comment by balanceiskey** [comment]
@benthemonkey Probably worth mentioning somewhere in the PR description, the sister PRs that are coming to `forest` and `kudzu` that will make use of this.

**Review by balanceiskey — APPROVED** [review]
@benthemonkey Dig it, nothing blocking from me here.

**Review by iamtheozzy — APPROVED** [review]
Looks good to me!

**Review by izzywyatt — APPROVED** [review]
LGTM

**Pull request merged**
